FROM  python:3.13

COPY --from=ghcr.io/astral-sh/uv:latest /uv /bin

WORKDIR  /code

COPY pyproject.toml .python-version uv.lock ./

RUN uv sync --locked 


COPY ingest_data.py .

ENV PATH="/code/.venv/bin:$PATH"

ENTRYPOINT ["uv","run", "python","ingest_data.py" ]